"""Initial migration

Revision ID: a1065c270f94
Revises: 
Create Date: 2026-05-07 17:17:52.429407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1065c270f94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.Text(), nullable=False),
    sa.Column('exercise_description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.SmallInteger(), nullable=True),
    sa.Column('recomended_duration', sa.Integer(), nullable=True),
    sa.Column('recomended_reps', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('league',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_table('metric',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.Text(), nullable=False),
    sa.Column('metric_description', sa.Text(), nullable=True),
    sa.Column('metric_category', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.Text(), nullable=False),
    sa.Column('zone', sa.String(length=3), nullable=True),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('benchmark',
    sa.Column('benchmark_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('mean', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('standard_deviation', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.metric_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('benchmark_id')
    )
    op.create_table('exercise_for_metric',
    sa.Column('exercise_for_metric_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.metric_id'], ),
    sa.PrimaryKeyConstraint('exercise_for_metric_id')
    )
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('coach_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.league_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.Text(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('national_team', sa.Text(), nullable=True),
    sa.Column('position', sa.String(length=3), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_login')
    )
    op.create_table('cluster_analysis',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('trust_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_table('report',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('season_metric',
    sa.Column('season_metric_id', sa.Integer(), nullable=False),
    sa.Column('season_start_year', sa.SmallInteger(), nullable=True),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('season_metric_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.metric_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('season_metric_id')
    )
    op.create_table('exercise_in_report',
    sa.Column('exercise_in_report_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['report.report_id'], ),
    sa.PrimaryKeyConstraint('exercise_in_report_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_in_report')
    op.drop_table('season_metric')
    op.drop_table('report')
    op.drop_table('cluster_analysis')
    op.drop_table('user')
    op.drop_table('player')
    op.drop_table('team')
    op.drop_table('exercise_for_metric')
    op.drop_table('benchmark')
    op.drop_table('role')
    op.drop_table('metric')
    op.drop_table('league')
    op.drop_table('exercise')
    # ### end Alembic commands ###
